name: wdywtg
description: "Where do you want to go today?"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  mockito: ^5.4.5
  collection: ^1.19.1

  # network
  dio: ^5.8.0
  retrofit: ^4.4.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  # logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0

  # di
  get_it: ^8.0.3

  # data
  floor: ^1.5.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  timezone: ^0.10.0

  # bloc
  flutter_bloc: ^9.0.0
  equatable: ^2.0.0
  rxdart: ^0.28.0

  # location
  geolocator: ^11.0.0
  app_settings: ^6.1.1

  # showcase
  showcaseview: ^4.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  weather_icons: ^3.0.0
  country_flags: ^3.0.0
  palette_generator: ^0.3.3+6
  lottie: ^3.3.1
  flutter_keyboard_visibility: ^6.0.0

  # firebase and ai
  firebase_core: ^3.13.0
  firebase_vertexai: ^1.5.0
  firebase_app_check: ^0.3.2+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  floor_generator: ^1.5.0

  # network
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/image/
    - assets/lottie/